/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.Api;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ChangePasswordRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangePasswordRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangePasswordRequest
        //private ChangePasswordRequest instance;

        public ChangePasswordRequestTests()
        {
            // TODO uncomment below to create an instance of ChangePasswordRequest
            //instance = new ChangePasswordRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangePasswordRequest
        /// </summary>
        [Fact]
        public void ChangePasswordRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChangePasswordRequest
            //Assert.IsType<ChangePasswordRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Fact]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
        /// <summary>
        /// Test the property 'NewPasswordConfirm'
        /// </summary>
        [Fact]
        public void NewPasswordConfirmTest()
        {
            // TODO unit test for the property 'NewPasswordConfirm'
        }

    }

}
