/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.Api;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CriteriaAggregationsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CriteriaAggregationsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CriteriaAggregationsInner
        //private CriteriaAggregationsInner instance;

        public CriteriaAggregationsInnerTests()
        {
            // TODO uncomment below to create an instance of CriteriaAggregationsInner
            //instance = new CriteriaAggregationsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CriteriaAggregationsInner
        /// </summary>
        [Fact]
        public void CriteriaAggregationsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CriteriaAggregationsInner
            //Assert.IsType<CriteriaAggregationsInner>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

    }

}
