/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.StoreApi;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing Failure
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FailureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Failure
        //private Failure instance;

        public FailureTests()
        {
            // TODO uncomment below to create an instance of Failure
            //instance = new Failure();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Failure
        /// </summary>
        [Fact]
        public void FailureInstanceTest()
        {
            // TODO uncomment below to test "IsType" Failure
            //Assert.IsType<Failure>(instance);
        }


        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
