/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.StoreApi;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing OrderAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderAddress
        //private OrderAddress instance;

        public OrderAddressTests()
        {
            // TODO uncomment below to create an instance of OrderAddress
            //instance = new OrderAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderAddress
        /// </summary>
        [Fact]
        public void OrderAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderAddress
            //Assert.IsType<OrderAddress>(instance);
        }


        /// <summary>
        /// Test the property 'CountryId'
        /// </summary>
        [Fact]
        public void CountryIdTest()
        {
            // TODO unit test for the property 'CountryId'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'Zipcode'
        /// </summary>
        [Fact]
        public void ZipcodeTest()
        {
            // TODO unit test for the property 'Zipcode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'VersionId'
        /// </summary>
        [Fact]
        public void VersionIdTest()
        {
            // TODO unit test for the property 'VersionId'
        }
        /// <summary>
        /// Test the property 'CountryStateId'
        /// </summary>
        [Fact]
        public void CountryStateIdTest()
        {
            // TODO unit test for the property 'CountryStateId'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Fact]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'VatId'
        /// </summary>
        [Fact]
        public void VatIdTest()
        {
            // TODO unit test for the property 'VatId'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'AdditionalAddressLine1'
        /// </summary>
        [Fact]
        public void AdditionalAddressLine1Test()
        {
            // TODO unit test for the property 'AdditionalAddressLine1'
        }
        /// <summary>
        /// Test the property 'AdditionalAddressLine2'
        /// </summary>
        [Fact]
        public void AdditionalAddressLine2Test()
        {
            // TODO unit test for the property 'AdditionalAddressLine2'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CountryState'
        /// </summary>
        [Fact]
        public void CountryStateTest()
        {
            // TODO unit test for the property 'CountryState'
        }
        /// <summary>
        /// Test the property 'Salutation'
        /// </summary>
        [Fact]
        public void SalutationTest()
        {
            // TODO unit test for the property 'Salutation'
        }

    }

}
