/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.Api;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing Product
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Product
        //private Product instance;

        public ProductTests()
        {
            // TODO uncomment below to create an instance of Product
            //instance = new Product();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Product
        /// </summary>
        [Fact]
        public void ProductInstanceTest()
        {
            // TODO uncomment below to test "IsType" Product
            //Assert.IsType<Product>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'VersionId'
        /// </summary>
        [Fact]
        public void VersionIdTest()
        {
            // TODO unit test for the property 'VersionId'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'ParentVersionId'
        /// </summary>
        [Fact]
        public void ParentVersionIdTest()
        {
            // TODO unit test for the property 'ParentVersionId'
        }
        /// <summary>
        /// Test the property 'ManufacturerId'
        /// </summary>
        [Fact]
        public void ManufacturerIdTest()
        {
            // TODO unit test for the property 'ManufacturerId'
        }
        /// <summary>
        /// Test the property 'ProductManufacturerVersionId'
        /// </summary>
        [Fact]
        public void ProductManufacturerVersionIdTest()
        {
            // TODO unit test for the property 'ProductManufacturerVersionId'
        }
        /// <summary>
        /// Test the property 'UnitId'
        /// </summary>
        [Fact]
        public void UnitIdTest()
        {
            // TODO unit test for the property 'UnitId'
        }
        /// <summary>
        /// Test the property 'TaxId'
        /// </summary>
        [Fact]
        public void TaxIdTest()
        {
            // TODO unit test for the property 'TaxId'
        }
        /// <summary>
        /// Test the property 'CoverId'
        /// </summary>
        [Fact]
        public void CoverIdTest()
        {
            // TODO unit test for the property 'CoverId'
        }
        /// <summary>
        /// Test the property 'ProductMediaVersionId'
        /// </summary>
        [Fact]
        public void ProductMediaVersionIdTest()
        {
            // TODO unit test for the property 'ProductMediaVersionId'
        }
        /// <summary>
        /// Test the property 'DeliveryTimeId'
        /// </summary>
        [Fact]
        public void DeliveryTimeIdTest()
        {
            // TODO unit test for the property 'DeliveryTimeId'
        }
        /// <summary>
        /// Test the property 'CanonicalProductId'
        /// </summary>
        [Fact]
        public void CanonicalProductIdTest()
        {
            // TODO unit test for the property 'CanonicalProductId'
        }
        /// <summary>
        /// Test the property 'CmsPageId'
        /// </summary>
        [Fact]
        public void CmsPageIdTest()
        {
            // TODO unit test for the property 'CmsPageId'
        }
        /// <summary>
        /// Test the property 'CmsPageVersionId'
        /// </summary>
        [Fact]
        public void CmsPageVersionIdTest()
        {
            // TODO unit test for the property 'CmsPageVersionId'
        }
        /// <summary>
        /// Test the property 'ProductNumber'
        /// </summary>
        [Fact]
        public void ProductNumberTest()
        {
            // TODO unit test for the property 'ProductNumber'
        }
        /// <summary>
        /// Test the property 'Stock'
        /// </summary>
        [Fact]
        public void StockTest()
        {
            // TODO unit test for the property 'Stock'
        }
        /// <summary>
        /// Test the property 'RestockTime'
        /// </summary>
        [Fact]
        public void RestockTimeTest()
        {
            // TODO unit test for the property 'RestockTime'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'AvailableStock'
        /// </summary>
        [Fact]
        public void AvailableStockTest()
        {
            // TODO unit test for the property 'AvailableStock'
        }
        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }
        /// <summary>
        /// Test the property 'IsCloseout'
        /// </summary>
        [Fact]
        public void IsCloseoutTest()
        {
            // TODO unit test for the property 'IsCloseout'
        }
        /// <summary>
        /// Test the property 'DisplayGroup'
        /// </summary>
        [Fact]
        public void DisplayGroupTest()
        {
            // TODO unit test for the property 'DisplayGroup'
        }
        /// <summary>
        /// Test the property 'MainVariantId'
        /// </summary>
        [Fact]
        public void MainVariantIdTest()
        {
            // TODO unit test for the property 'MainVariantId'
        }
        /// <summary>
        /// Test the property 'ManufacturerNumber'
        /// </summary>
        [Fact]
        public void ManufacturerNumberTest()
        {
            // TODO unit test for the property 'ManufacturerNumber'
        }
        /// <summary>
        /// Test the property 'Ean'
        /// </summary>
        [Fact]
        public void EanTest()
        {
            // TODO unit test for the property 'Ean'
        }
        /// <summary>
        /// Test the property 'PurchaseSteps'
        /// </summary>
        [Fact]
        public void PurchaseStepsTest()
        {
            // TODO unit test for the property 'PurchaseSteps'
        }
        /// <summary>
        /// Test the property 'MaxPurchase'
        /// </summary>
        [Fact]
        public void MaxPurchaseTest()
        {
            // TODO unit test for the property 'MaxPurchase'
        }
        /// <summary>
        /// Test the property 'MinPurchase'
        /// </summary>
        [Fact]
        public void MinPurchaseTest()
        {
            // TODO unit test for the property 'MinPurchase'
        }
        /// <summary>
        /// Test the property 'PurchaseUnit'
        /// </summary>
        [Fact]
        public void PurchaseUnitTest()
        {
            // TODO unit test for the property 'PurchaseUnit'
        }
        /// <summary>
        /// Test the property 'ReferenceUnit'
        /// </summary>
        [Fact]
        public void ReferenceUnitTest()
        {
            // TODO unit test for the property 'ReferenceUnit'
        }
        /// <summary>
        /// Test the property 'ShippingFree'
        /// </summary>
        [Fact]
        public void ShippingFreeTest()
        {
            // TODO unit test for the property 'ShippingFree'
        }
        /// <summary>
        /// Test the property 'MarkAsTopseller'
        /// </summary>
        [Fact]
        public void MarkAsTopsellerTest()
        {
            // TODO unit test for the property 'MarkAsTopseller'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'ReleaseDate'
        /// </summary>
        [Fact]
        public void ReleaseDateTest()
        {
            // TODO unit test for the property 'ReleaseDate'
        }
        /// <summary>
        /// Test the property 'RatingAverage'
        /// </summary>
        [Fact]
        public void RatingAverageTest()
        {
            // TODO unit test for the property 'RatingAverage'
        }
        /// <summary>
        /// Test the property 'CategoryTree'
        /// </summary>
        [Fact]
        public void CategoryTreeTest()
        {
            // TODO unit test for the property 'CategoryTree'
        }
        /// <summary>
        /// Test the property 'PropertyIds'
        /// </summary>
        [Fact]
        public void PropertyIdsTest()
        {
            // TODO unit test for the property 'PropertyIds'
        }
        /// <summary>
        /// Test the property 'OptionIds'
        /// </summary>
        [Fact]
        public void OptionIdsTest()
        {
            // TODO unit test for the property 'OptionIds'
        }
        /// <summary>
        /// Test the property 'CategoryIds'
        /// </summary>
        [Fact]
        public void CategoryIdsTest()
        {
            // TODO unit test for the property 'CategoryIds'
        }
        /// <summary>
        /// Test the property 'ChildCount'
        /// </summary>
        [Fact]
        public void ChildCountTest()
        {
            // TODO unit test for the property 'ChildCount'
        }
        /// <summary>
        /// Test the property 'Sales'
        /// </summary>
        [Fact]
        public void SalesTest()
        {
            // TODO unit test for the property 'Sales'
        }
        /// <summary>
        /// Test the property 'MetaDescription'
        /// </summary>
        [Fact]
        public void MetaDescriptionTest()
        {
            // TODO unit test for the property 'MetaDescription'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Fact]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'MetaTitle'
        /// </summary>
        [Fact]
        public void MetaTitleTest()
        {
            // TODO unit test for the property 'MetaTitle'
        }
        /// <summary>
        /// Test the property 'PackUnit'
        /// </summary>
        [Fact]
        public void PackUnitTest()
        {
            // TODO unit test for the property 'PackUnit'
        }
        /// <summary>
        /// Test the property 'PackUnitPlural'
        /// </summary>
        [Fact]
        public void PackUnitPluralTest()
        {
            // TODO unit test for the property 'PackUnitPlural'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'CalculatedPrice'
        /// </summary>
        [Fact]
        public void CalculatedPriceTest()
        {
            // TODO unit test for the property 'CalculatedPrice'
        }
        /// <summary>
        /// Test the property 'CalculatedPrices'
        /// </summary>
        [Fact]
        public void CalculatedPricesTest()
        {
            // TODO unit test for the property 'CalculatedPrices'
        }
        /// <summary>
        /// Test the property 'CalculatedMaxPurchase'
        /// </summary>
        [Fact]
        public void CalculatedMaxPurchaseTest()
        {
            // TODO unit test for the property 'CalculatedMaxPurchase'
        }
        /// <summary>
        /// Test the property 'CalculatedCheapestPrice'
        /// </summary>
        [Fact]
        public void CalculatedCheapestPriceTest()
        {
            // TODO unit test for the property 'CalculatedCheapestPrice'
        }
        /// <summary>
        /// Test the property 'IsNew'
        /// </summary>
        [Fact]
        public void IsNewTest()
        {
            // TODO unit test for the property 'IsNew'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Translated'
        /// </summary>
        [Fact]
        public void TranslatedTest()
        {
            // TODO unit test for the property 'Translated'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Fact]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
        /// <summary>
        /// Test the property 'DeliveryTime'
        /// </summary>
        [Fact]
        public void DeliveryTimeTest()
        {
            // TODO unit test for the property 'DeliveryTime'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Fact]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Fact]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'Cover'
        /// </summary>
        [Fact]
        public void CoverTest()
        {
            // TODO unit test for the property 'Cover'
        }
        /// <summary>
        /// Test the property 'CmsPage'
        /// </summary>
        [Fact]
        public void CmsPageTest()
        {
            // TODO unit test for the property 'CmsPage'
        }
        /// <summary>
        /// Test the property 'CanonicalProduct'
        /// </summary>
        [Fact]
        public void CanonicalProductTest()
        {
            // TODO unit test for the property 'CanonicalProduct'
        }
        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Fact]
        public void MediaTest()
        {
            // TODO unit test for the property 'Media'
        }
        /// <summary>
        /// Test the property 'CrossSellings'
        /// </summary>
        [Fact]
        public void CrossSellingsTest()
        {
            // TODO unit test for the property 'CrossSellings'
        }
        /// <summary>
        /// Test the property 'ConfiguratorSettings'
        /// </summary>
        [Fact]
        public void ConfiguratorSettingsTest()
        {
            // TODO unit test for the property 'ConfiguratorSettings'
        }
        /// <summary>
        /// Test the property 'ProductReviews'
        /// </summary>
        [Fact]
        public void ProductReviewsTest()
        {
            // TODO unit test for the property 'ProductReviews'
        }
        /// <summary>
        /// Test the property 'MainCategories'
        /// </summary>
        [Fact]
        public void MainCategoriesTest()
        {
            // TODO unit test for the property 'MainCategories'
        }
        /// <summary>
        /// Test the property 'SeoUrls'
        /// </summary>
        [Fact]
        public void SeoUrlsTest()
        {
            // TODO unit test for the property 'SeoUrls'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Streams'
        /// </summary>
        [Fact]
        public void StreamsTest()
        {
            // TODO unit test for the property 'Streams'
        }
        /// <summary>
        /// Test the property 'CategoriesRo'
        /// </summary>
        [Fact]
        public void CategoriesRoTest()
        {
            // TODO unit test for the property 'CategoriesRo'
        }
        /// <summary>
        /// Test the property 'SeoCategory'
        /// </summary>
        [Fact]
        public void SeoCategoryTest()
        {
            // TODO unit test for the property 'SeoCategory'
        }

    }

}
