/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.StoreApi;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ReadProductReviews200ResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReadProductReviews200ResponseAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReadProductReviews200ResponseAllOf
        //private ReadProductReviews200ResponseAllOf instance;

        public ReadProductReviews200ResponseAllOfTests()
        {
            // TODO uncomment below to create an instance of ReadProductReviews200ResponseAllOf
            //instance = new ReadProductReviews200ResponseAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReadProductReviews200ResponseAllOf
        /// </summary>
        [Fact]
        public void ReadProductReviews200ResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReadProductReviews200ResponseAllOf
            //Assert.IsType<ReadProductReviews200ResponseAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Fact]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }

    }

}
