/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.StoreApi;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing RecoveryPasswordRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecoveryPasswordRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecoveryPasswordRequest
        //private RecoveryPasswordRequest instance;

        public RecoveryPasswordRequestTests()
        {
            // TODO uncomment below to create an instance of RecoveryPasswordRequest
            //instance = new RecoveryPasswordRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecoveryPasswordRequest
        /// </summary>
        [Fact]
        public void RecoveryPasswordRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecoveryPasswordRequest
            //Assert.IsType<RecoveryPasswordRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Fact]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
        /// <summary>
        /// Test the property 'NewPasswordConfirm'
        /// </summary>
        [Fact]
        public void NewPasswordConfirmTest()
        {
            // TODO unit test for the property 'NewPasswordConfirm'
        }

    }

}
