/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.Api;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing SendContactMailRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendContactMailRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendContactMailRequest
        //private SendContactMailRequest instance;

        public SendContactMailRequestTests()
        {
            // TODO uncomment below to create an instance of SendContactMailRequest
            //instance = new SendContactMailRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendContactMailRequest
        /// </summary>
        [Fact]
        public void SendContactMailRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendContactMailRequest
            //Assert.IsType<SendContactMailRequest>(instance);
        }


        /// <summary>
        /// Test the property 'SalutationId'
        /// </summary>
        [Fact]
        public void SalutationIdTest()
        {
            // TODO unit test for the property 'SalutationId'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'NavigationId'
        /// </summary>
        [Fact]
        public void NavigationIdTest()
        {
            // TODO unit test for the property 'NavigationId'
        }
        /// <summary>
        /// Test the property 'SlotId'
        /// </summary>
        [Fact]
        public void SlotIdTest()
        {
            // TODO unit test for the property 'SlotId'
        }
        /// <summary>
        /// Test the property 'CmsPageType'
        /// </summary>
        [Fact]
        public void CmsPageTypeTest()
        {
            // TODO unit test for the property 'CmsPageType'
        }
        /// <summary>
        /// Test the property 'EntityName'
        /// </summary>
        [Fact]
        public void EntityNameTest()
        {
            // TODO unit test for the property 'EntityName'
        }

    }

}
