/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.StoreApi;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing SuccessResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuccessResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuccessResponse
        //private SuccessResponse instance;

        public SuccessResponseTests()
        {
            // TODO uncomment below to create an instance of SuccessResponse
            //instance = new SuccessResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuccessResponse
        /// </summary>
        [Fact]
        public void SuccessResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuccessResponse
            //Assert.IsType<SuccessResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
