skipValidateSpec:
gitRepoId: ShopwareSharp
gitUserId: cmgt
# library: generichost
library: httpclient
additionalProperties:
  netCoreProjectFile: true
  packageName: ShopwareSharp
  packageVersion: 0.1.0
  targetFramework: net6.0