/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using ShopwareSharp.Client;
using ShopwareSharp.Model;

namespace ShopwareSharp.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentMethodApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Loads all available payment methods
        /// </summary>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <returns>ReadPaymentMethod200Response</returns>
        ReadPaymentMethod200Response ReadPaymentMethod(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest);

        /// <summary>
        /// Loads all available payment methods
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <returns>ApiResponse of ReadPaymentMethod200Response</returns>
        ApiResponse<ReadPaymentMethod200Response> ReadPaymentMethodWithHttpInfo(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentMethodApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Loads all available payment methods
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ReadPaymentMethod200Response</returns>
        System.Threading.Tasks.Task<ReadPaymentMethod200Response> ReadPaymentMethodAsync(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Loads all available payment methods
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ReadPaymentMethod200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReadPaymentMethod200Response>> ReadPaymentMethodWithHttpInfoAsync(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentMethodApi : IPaymentMethodApiSync, IPaymentMethodApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PaymentMethodApi : IDisposable, IPaymentMethodApi
    {
        private ShopwareSharp.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PaymentMethodApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PaymentMethodApi(string basePath)
        {
            this.Configuration = ShopwareSharp.Client.Configuration.MergeConfigurations(
                ShopwareSharp.Client.GlobalConfiguration.Instance,
                new ShopwareSharp.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ShopwareSharp.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ShopwareSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PaymentMethodApi(ShopwareSharp.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ShopwareSharp.Client.Configuration.MergeConfigurations(
                ShopwareSharp.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ShopwareSharp.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ShopwareSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PaymentMethodApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PaymentMethodApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ShopwareSharp.Client.Configuration.MergeConfigurations(
                ShopwareSharp.Client.GlobalConfiguration.Instance,
                new ShopwareSharp.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ShopwareSharp.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ShopwareSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PaymentMethodApi(HttpClient client, ShopwareSharp.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ShopwareSharp.Client.Configuration.MergeConfigurations(
                ShopwareSharp.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ShopwareSharp.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ShopwareSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PaymentMethodApi(ShopwareSharp.Client.ISynchronousClient client, ShopwareSharp.Client.IAsynchronousClient asyncClient, ShopwareSharp.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ShopwareSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public ShopwareSharp.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ShopwareSharp.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ShopwareSharp.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ShopwareSharp.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ShopwareSharp.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Loads all available payment methods 
        /// </summary>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <returns>ReadPaymentMethod200Response</returns>
        public ReadPaymentMethod200Response ReadPaymentMethod(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest)
        {
            ShopwareSharp.Client.ApiResponse<ReadPaymentMethod200Response> localVarResponse = ReadPaymentMethodWithHttpInfo(contentType, accept, readPaymentMethodRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Loads all available payment methods 
        /// </summary>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <returns>ApiResponse of ReadPaymentMethod200Response</returns>
        public ShopwareSharp.Client.ApiResponse<ReadPaymentMethod200Response> ReadPaymentMethodWithHttpInfo(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest)
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ShopwareSharp.Client.ApiException(400, "Missing required parameter 'contentType' when calling PaymentMethodApi->ReadPaymentMethod");

            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ShopwareSharp.Client.ApiException(400, "Missing required parameter 'accept' when calling PaymentMethodApi->ReadPaymentMethod");

            // verify the required parameter 'readPaymentMethodRequest' is set
            if (readPaymentMethodRequest == null)
                throw new ShopwareSharp.Client.ApiException(400, "Missing required parameter 'readPaymentMethodRequest' when calling PaymentMethodApi->ReadPaymentMethod");

            ShopwareSharp.Client.RequestOptions localVarRequestOptions = new ShopwareSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ShopwareSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ShopwareSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("Content-Type", ShopwareSharp.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("Accept", ShopwareSharp.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.Data = readPaymentMethodRequest;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sw-access-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("sw-access-key", this.Configuration.GetApiKeyWithPrefix("sw-access-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ReadPaymentMethod200Response>("/payment-method", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadPaymentMethod", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Loads all available payment methods 
        /// </summary>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ReadPaymentMethod200Response</returns>
        public async System.Threading.Tasks.Task<ReadPaymentMethod200Response> ReadPaymentMethodAsync(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ShopwareSharp.Client.ApiResponse<ReadPaymentMethod200Response> localVarResponse = await ReadPaymentMethodWithHttpInfoAsync(contentType, accept, readPaymentMethodRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Loads all available payment methods 
        /// </summary>
        /// <exception cref="ShopwareSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType">Content type of the request</param>
        /// <param name="accept">Accepted response content types</param>
        /// <param name="readPaymentMethodRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ReadPaymentMethod200Response)</returns>
        public async System.Threading.Tasks.Task<ShopwareSharp.Client.ApiResponse<ReadPaymentMethod200Response>> ReadPaymentMethodWithHttpInfoAsync(string contentType, string accept, ReadPaymentMethodRequest readPaymentMethodRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
                throw new ShopwareSharp.Client.ApiException(400, "Missing required parameter 'contentType' when calling PaymentMethodApi->ReadPaymentMethod");

            // verify the required parameter 'accept' is set
            if (accept == null)
                throw new ShopwareSharp.Client.ApiException(400, "Missing required parameter 'accept' when calling PaymentMethodApi->ReadPaymentMethod");

            // verify the required parameter 'readPaymentMethodRequest' is set
            if (readPaymentMethodRequest == null)
                throw new ShopwareSharp.Client.ApiException(400, "Missing required parameter 'readPaymentMethodRequest' when calling PaymentMethodApi->ReadPaymentMethod");


            ShopwareSharp.Client.RequestOptions localVarRequestOptions = new ShopwareSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ShopwareSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ShopwareSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("Content-Type", ShopwareSharp.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("Accept", ShopwareSharp.Client.ClientUtils.ParameterToString(accept)); // header parameter
            localVarRequestOptions.Data = readPaymentMethodRequest;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sw-access-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("sw-access-key", this.Configuration.GetApiKeyWithPrefix("sw-access-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ReadPaymentMethod200Response>("/payment-method", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadPaymentMethod", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
