// <auto-generated>
/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;

namespace ShopwareSharp.Model
{
    /// <summary>
    /// OrderSetPaymentRequest
    /// </summary>
    public partial class OrderSetPaymentRequest : IEquatable<OrderSetPaymentRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderSetPaymentRequest" /> class.
        /// </summary>
        /// <param name="paymentMethodId">The identifier of the paymentMethod to be set (required)</param>
        /// <param name="orderId">The identifier of the order. (required)</param>
        public OrderSetPaymentRequest(string paymentMethodId, string orderId)
        {
            if (paymentMethodId == null)
                throw new ArgumentNullException("paymentMethodId is a required property for OrderSetPaymentRequest and cannot be null.");

            if (orderId == null)
                throw new ArgumentNullException("orderId is a required property for OrderSetPaymentRequest and cannot be null.");

            PaymentMethodId = paymentMethodId;
            OrderId = orderId;
        }

        /// <summary>
        /// The identifier of the paymentMethod to be set
        /// </summary>
        /// <value>The identifier of the paymentMethod to be set</value>
        [JsonPropertyName("paymentMethodId")]
        public string PaymentMethodId { get; set; }

        /// <summary>
        /// The identifier of the order.
        /// </summary>
        /// <value>The identifier of the order.</value>
        [JsonPropertyName("orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderSetPaymentRequest {\n");
            sb.Append("  PaymentMethodId: ").Append(PaymentMethodId).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? input)
        {
            return this.Equals(input as OrderSetPaymentRequest);
        }

        /// <summary>
        /// Returns true if OrderSetPaymentRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderSetPaymentRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderSetPaymentRequest? input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PaymentMethodId == input.PaymentMethodId ||
                    (this.PaymentMethodId != null &&
                    this.PaymentMethodId.Equals(input.PaymentMethodId))
                ) && 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PaymentMethodId != null)
                {
                    hashCode = (hashCode * 59) + this.PaymentMethodId.GetHashCode();
                }
                if (this.OrderId != null)
                {
                    hashCode = (hashCode * 59) + this.OrderId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
