/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.Api;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CustomFieldSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomFieldSetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomFieldSet
        //private CustomFieldSet instance;

        public CustomFieldSetTests()
        {
            // TODO uncomment below to create an instance of CustomFieldSet
            //instance = new CustomFieldSet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomFieldSet
        /// </summary>
        [Fact]
        public void CustomFieldSetInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomFieldSet
            //Assert.IsType<CustomFieldSet>(instance);
        }


        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
