/*
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.4.9999999.9999999-dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopwareSharp.Api;
using ShopwareSharp.Model;
using ShopwareSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopwareSharp.Test.Model
{
    /// <summary>
    ///  Class for testing HandlePaymentMethodRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HandlePaymentMethodRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HandlePaymentMethodRequest
        //private HandlePaymentMethodRequest instance;

        public HandlePaymentMethodRequestTests()
        {
            // TODO uncomment below to create an instance of HandlePaymentMethodRequest
            //instance = new HandlePaymentMethodRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HandlePaymentMethodRequest
        /// </summary>
        [Fact]
        public void HandlePaymentMethodRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" HandlePaymentMethodRequest
            //Assert.IsType<HandlePaymentMethodRequest>(instance);
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'FinishUrl'
        /// </summary>
        [Fact]
        public void FinishUrlTest()
        {
            // TODO unit test for the property 'FinishUrl'
        }
        /// <summary>
        /// Test the property 'ErrorUrl'
        /// </summary>
        [Fact]
        public void ErrorUrlTest()
        {
            // TODO unit test for the property 'ErrorUrl'
        }

    }

}
